# Version of Docker compose syntax
version: "3.9"

# Main block, one or more services can be used
services:
  # Main Django app
  app:
    build:
      # Root will be used as ctx
      context: .
      args:
        - DEV=true
    # Map ports from local machine with Docker container
    ports:
      - "8000:8000"
    # Map locale machine directory with Docker container directory
    # Reflect changes in container in local machine directory without re-run container
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    # Tell Docker compose that this service depends on following
    depends_on:
      - db

  # Database service
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    # Create initial config for 1st db creation (change in project)
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: